export const PERMISSIONS_CATALOG = [
    // DASHBOARD
    { key: 'dashboard.visualizar', modulo: 'Dashboard', grupo: 'Geral', nome: 'Ver dashboard principal', descricao: 'Acessar e visualizar o dashboard de acompanhamento principal.', nivel_risk: 'baixo', order: 10 },
    { key: 'dashboard.ver_indicadores_globais', modulo: 'Dashboard', grupo: 'Avançado', nome: 'Ver indicadores de toda a empresa', descricao: 'Ver métricas e resultados de chamados globais da empresa.', nivel_risk: 'medio', order: 20 },
    { key: 'dashboard.ver_indicadores_proprios', modulo: 'Dashboard', grupo: 'Básico', nome: 'Ver apenas indicadores próprios', descricao: 'Restringir a amostragem do dashboard somente aos indicadores pessoais do atendente.', nivel_risk: 'baixo', order: 30 },
    { key: 'dashboard.ver_sla', modulo: 'Dashboard', grupo: 'Controle', nome: 'Ver cartões e alertas de SLA', descricao: 'Ver painéis específicos de monitoramento de metas SLA na Home.', nivel_risk: 'baixo', order: 40 },
    { key: 'dashboard.ver_financeiro_operacional', modulo: 'Dashboard', grupo: 'Avançado', nome: 'Ver indicadores operacionais/financeiros', descricao: 'Ver metas ou indicadores financeiros operacionais se aplicável.', nivel_risk: 'alto', order: 50 },
    // CHAMADOS
    { key: 'tickets.visualizar', modulo: 'Chamados', grupo: 'Acesso', nome: 'Acessar módulo de chamados', descricao: 'Ver a lista ou grid de chamados.', nivel_risk: 'baixo', order: 100 },
    { key: 'tickets.ver_proprios', modulo: 'Chamados', grupo: 'Escopo', nome: 'Ver apenas chamados próprios', descricao: 'Restringir a listagem de chamados apenas aos vinculados ou criados por si.', nivel_risk: 'baixo', order: 110 },
    { key: 'tickets.ver_todos', modulo: 'Chamados', grupo: 'Escopo', nome: 'Ver todos os chamados', descricao: 'Permissão para visualizar qualquer chamado da empresa.', nivel_risk: 'medio', order: 120 },
    { key: 'tickets.ver_sem_responsavel', modulo: 'Chamados', grupo: 'Escopo', nome: 'Ver fila de chamados sem responsável', descricao: 'Visualizar a fila comum de chamados ainda não assumidos.', nivel_risk: 'baixo', order: 130 },
    { key: 'tickets.ver_por_categoria', modulo: 'Chamados', grupo: 'Filtros', nome: 'Visualizar em lote por categoria', descricao: 'Buscar e ver chamados com base nas categorias da empresa.', nivel_risk: 'baixo', order: 140 },
    { key: 'tickets.ver_detalhes', modulo: 'Chamados', grupo: 'Visualização', nome: 'Abrir detalhes de um chamado', descricao: 'Visualizar corpo do chamado, campo de respostas e dados específicos.', nivel_risk: 'baixo', order: 150 },
    { key: 'tickets.criar', modulo: 'Chamados', grupo: 'Ações', nome: 'Criar chamado manualmente', descricao: 'Criar um chamado de forma manual no sistema administrativo.', nivel_risk: 'baixo', order: 160 },
    { key: 'tickets.criar_para_cliente', modulo: 'Chamados', grupo: 'Ações', nome: 'Criar chamado em nome de outro solicitante', descricao: 'Criar chamado cujo autor registrado é um cliente de fora.', nivel_risk: 'medio', order: 170 },
    { key: 'tickets.editar', modulo: 'Chamados', grupo: 'Edição', nome: 'Editar dados básicos de chamado', descricao: 'Modificar dados nas propriedades gerais do chamado.', nivel_risk: 'baixo', order: 180 },
    { key: 'tickets.editar_titulo', modulo: 'Chamados', grupo: 'Edição', nome: 'Editar título do chamado', descricao: 'Modificar o título do chamado.', nivel_risk: 'baixo', order: 190 },
    { key: 'tickets.editar_descricao', modulo: 'Chamados', grupo: 'Edição', nome: 'Editar descrição do chamado', descricao: 'Permissão para retificar o relato original do chamado.', nivel_risk: 'baixo', order: 200 },
    { key: 'tickets.editar_categoria', modulo: 'Chamados', grupo: 'Propriedades', nome: 'Alterar categoria', descricao: 'Alterar a categoria do fluxo de trabalho do chamado.', nivel_risk: 'baixo', order: 210 },
    { key: 'tickets.editar_servico', modulo: 'Chamados', grupo: 'Propriedades', nome: 'Alterar serviço', descricao: 'Modificar o serviço preenchido nas propriedades do chamado.', nivel_risk: 'baixo', order: 220 },
    { key: 'tickets.editar_prioridade', modulo: 'Chamados', grupo: 'Propriedades', nome: 'Alterar prioridade', descricao: 'Subir ou descer o nível de urgência / prioridade.', nivel_risk: 'baixo', order: 230 },
    { key: 'tickets.editar_status', modulo: 'Chamados', grupo: 'Propriedades', nome: 'Alterar status', descricao: 'Mover chamado entre Novo, Em andamento, Pendente, etc.', nivel_risk: 'baixo', order: 240 },
    { key: 'tickets.finalizar', modulo: 'Chamados', grupo: 'Fechamento', nome: 'Resolver chamado', descricao: 'Marcar o chamado como resolvido.', nivel_risk: 'baixo', order: 250 },
    { key: 'tickets.fechar', modulo: 'Chamados', grupo: 'Fechamento', nome: 'Fechar definitivamente chamado', descricao: 'Dar encerramento total ao chamado impedindo ações públicas.', nivel_risk: 'baixo', order: 260 },
    { key: 'tickets.reabrir', modulo: 'Chamados', grupo: 'Fechamento', nome: 'Reabrir chamado', descricao: 'Reverter estado resolvido/fechado de volta a ativo.', nivel_risk: 'baixo', order: 270 },
    { key: 'tickets.excluir', modulo: 'Chamados', grupo: 'Perigosos', nome: 'Excluir chamado', descricao: 'Super exclusão física ou lógica sensível do chamado no banco de dados.', nivel_risk: 'critico', order: 280 },
    { key: 'tickets.arquivar', modulo: 'Chamados', grupo: 'Ações', nome: 'Arquivar chamado', descricao: 'Ocultar o chamado sem excluir fisicamente os dados.', nivel_risk: 'medio', order: 290 },
    { key: 'tickets.atribuir', modulo: 'Chamados', grupo: 'Atribuição', nome: 'Atribuir responsável', descricao: 'Delegar o chamado a qualquer agente de suporte disponível.', nivel_risk: 'baixo', order: 300 },
    { key: 'tickets.assumir', modulo: 'Chamados', grupo: 'Atribuição', nome: 'Assumir chamado', descricao: 'Atribuir-se como responsável do chamado.', nivel_risk: 'baixo', order: 310 },
    { key: 'tickets.transferir', modulo: 'Chamados', grupo: 'Atribuição', nome: 'Transferir chamado', descricao: 'Mudar a responsabilidade de um agente de suporte para outro.', nivel_risk: 'baixo', order: 320 },
    { key: 'tickets.remover_responsavel', modulo: 'Chamados', grupo: 'Atribuição', nome: 'Remover responsável', descricao: 'Remover o responsável do chamado deixando-o sem atribuição.', nivel_risk: 'baixo', order: 330 },
    { key: 'tickets.acoes_em_massa', modulo: 'Chamados', grupo: 'Ações', nome: 'Ações em massa', descricao: 'Alterar e encerrar múltiplos chamados simultaneamente.', nivel_risk: 'medio', order: 340 },
    { key: 'tickets.alterar_sla', modulo: 'Chamados', grupo: 'Controle', nome: 'Alterar dados/prazos de SLA', descricao: 'Redefinir datas limites e prazos de SLA individuais.', nivel_risk: 'alto', order: 350 },
    { key: 'tickets.ver_timeline', modulo: 'Chamados', grupo: 'Visualização', nome: 'Ver timeline/eventos do chamado', descricao: 'Visualizar auditoria interna de todas as ações ocorridas no chamado.', nivel_risk: 'baixo', order: 360 },
    { key: 'tickets.ver_tags', modulo: 'Chamados', grupo: 'Tags', nome: 'Ver tags', descricao: 'Visualizar etiquetas aplicadas.', nivel_risk: 'baixo', order: 370 },
    { key: 'tickets.gerenciar_tags', modulo: 'Chamados', grupo: 'Tags', nome: 'Adicionar/remover tags', descricao: 'Incluir novas etiquetas ou desvincular etiquetas existentes.', nivel_risk: 'baixo', order: 380 },
    { key: 'tickets.ver_campos_customizados', modulo: 'Chamados', grupo: 'Atributos', nome: 'Ver campos customizados', descricao: 'Ver formulários auxiliares preenchidos para o chamado.', nivel_risk: 'baixo', order: 390 },
    { key: 'tickets.editar_campos_customizados', modulo: 'Chamados', grupo: 'Atributos', nome: 'Editar campos customizados', descricao: 'Preencher ou alterar as respostas dos campos adicionais.', nivel_risk: 'baixo', order: 400 },
    { key: 'tickets.ver_origem_email', modulo: 'Chamados', grupo: 'Visualização', nome: 'Ver dados técnicos de e-mail / origem', descricao: 'Visualizar MIME Headers e e-mail bruto de origem se canal unificado.', nivel_risk: 'baixo', order: 410 },
    { key: 'tickets.ver_dados_sensiveis', modulo: 'Chamados', grupo: 'Visualização', nome: 'Ver dados sensíveis', descricao: 'Ver identificadores pessoais adicionais do cliente solicitante.', nivel_risk: 'medio', order: 420 },
    { key: 'tickets.editar_origem', modulo: 'Chamados', grupo: 'Propriedades', nome: 'Alterar origem do chamado', descricao: 'Alterar manualmente o canal/origem registrado no chamado.', nivel_risk: 'alto', order: 430 },
    // MENSAGENS DO CHAMADO
    { key: 'ticket_mensagens.visualizar', modulo: 'Mensagens do Chamado', grupo: 'Visualização', nome: 'Ver mensagens públicas', descricao: 'Ler as mensagens abertas que o cliente também lê.', nivel_risk: 'baixo', order: 500 },
    { key: 'ticket_mensagens.responder', modulo: 'Mensagens do Chamado', grupo: 'Respostas', nome: 'Enviar resposta pública ao cliente', descricao: 'Falar de forma oficial com o solicitante no chamado.', nivel_risk: 'baixo', order: 510 },
    { key: 'ticket_mensagens.editar_propria', modulo: 'Mensagens do Chamado', grupo: 'Modificações', nome: 'Editar própria mensagem', descricao: 'Corrigir ou reescrever uma fala própria anterior.', nivel_risk: 'baixo', order: 520 },
    { key: 'ticket_mensagens.editar_qualquer', modulo: 'Mensagens do Chamado', grupo: 'Modificações', nome: 'Editar mensagem de qualquer usuário', descricao: 'Supervisores retificando mensagens de terceiros.', nivel_risk: 'medio', order: 530 },
    { key: 'ticket_mensagens.excluir_propria', modulo: 'Mensagens do Chamado', grupo: 'Modificações', nome: 'Excluir própria mensagem', descricao: 'Remover uma mensagem escrita por você mesmo.', nivel_risk: 'baixo', order: 540 },
    { key: 'ticket_mensagens.excluir_qualquer', modulo: 'Mensagens do Chamado', grupo: 'Modificações', nome: 'Excluir qualquer mensagem', descricao: 'Limpar do histórico mensagens de outros atendentes.', nivel_risk: 'medio', order: 550 },
    { key: 'ticket_mensagens.comentar_interno', modulo: 'Mensagens do Chamado', grupo: 'Notas Internas', nome: 'Criar comentário interno', descricao: 'Fazer comentários privados que o solicitante externo não visualiza.', nivel_risk: 'baixo', order: 560 },
    { key: 'ticket_mensagens.ver_internos', modulo: 'Mensagens do Chamado', grupo: 'Notas Internas', nome: 'Ver comentários internos', descricao: 'Acessar e poder ler os comentários privados da equipe de suporte.', nivel_risk: 'baixo', order: 570 },
    { key: 'ticket_mensagens.anexar', modulo: 'Mensagens do Chamado', grupo: 'Arquivos', nome: 'Enviar anexos', descricao: 'Subir arquivos, PDFs e imagens na caixa de resposta.', nivel_risk: 'baixo', order: 580 },
    { key: 'ticket_mensagens.baixar_anexos', modulo: 'Mensagens do Chamado', grupo: 'Arquivos', nome: 'Baixar anexos', descricao: 'Visualizar e baixar mídia/documentos enviados.', nivel_risk: 'baixo', order: 590 },
    { key: 'ticket_mensagens.excluir_anexos', modulo: 'Mensagens do Chamado', grupo: 'Arquivos', nome: 'Excluir anexos', descricao: 'Apagar arquivos persistidos no chamado.', nivel_risk: 'medio', order: 600 },
    // SLA
    { key: 'sla.visualizar', modulo: 'SLA', grupo: 'Acesso', nome: 'Ver informações de SLA', descricao: 'Visualizar prazos e tempos limites de SLA.', nivel_risk: 'baixo', order: 700 },
    { key: 'sla.gerenciar_politicas', modulo: 'SLA', grupo: 'Políticas', nome: 'Criar/editar políticas de SLA', descricao: 'Cadastrar metas, regras de triagem de acordo com prioridade e prazos globais.', nivel_risk: 'alto', order: 710 },
    { key: 'sla.pausar', modulo: 'SLA', grupo: 'Operação', nome: 'Pausar SLA manualmente', descricao: 'Congelar o cronômetro de um chamado sob justificativa.', nivel_risk: 'medio', order: 720 },
    { key: 'sla.retomar', modulo: 'SLA', grupo: 'Operação', nome: 'Retomar SLA', descricao: 'Voltar a contar o relógio de SLA após retorno ou verificação.', nivel_risk: 'baixo', order: 730 },
    { key: 'sla.ignorar_violacao', modulo: 'SLA', grupo: 'Justificativas', nome: 'Marcar violação como ignorada/justificada', descricao: 'Ignorar o estouro de SLA no log oficial devido a força maior.', nivel_risk: 'alto', order: 740 },
    { key: 'sla.ver_relatorios', modulo: 'SLA', grupo: 'Escopo Relatórios', nome: 'Ver relatórios de SLA', descricao: 'Ver estatísticas de conformidade com tempo de primeira resposta e resolução.', nivel_risk: 'medio', order: 750 },
    { key: 'sla.configurar_calendario', modulo: 'SLA', grupo: 'Operação', nome: 'Configurar calendário comercial', descricao: 'Feriados, horas úteis estruturadas da operação.', nivel_risk: 'medio', order: 760 },
    // AUTOMAÇÕES
    { key: 'automacoes.visualizar', modulo: 'Automações', grupo: 'Acesso', nome: 'Ver automações', descricao: 'Acessar e ver a listagem de gatilhos automáticos do sistema.', nivel_risk: 'baixo', order: 800 },
    { key: 'automacoes.criar', modulo: 'Automações', grupo: 'Modificações', nome: 'Criar automação', descricao: 'Criar regras reativas de alteração de chamados.', nivel_risk: 'alto', order: 810 },
    { key: 'automacoes.editar', modulo: 'Automações', grupo: 'Modificações', nome: 'Editar automação', descricao: 'Modificar condições operacionais de gatilhos.', nivel_risk: 'alto', order: 820 },
    { key: 'automacoes.ativar_desativar', modulo: 'Automações', grupo: 'Controle', nome: 'Ativar / desativar automação', descricao: 'Ligar/Desligar automações cadastradas.', nivel_risk: 'medio', order: 830 },
    { key: 'automacoes.excluir', modulo: 'Automações', grupo: 'Perigosos', nome: 'Excluir automação', descricao: 'Excluir fisicamente a regra de automação.', nivel_risk: 'critico', order: 840 },
    { key: 'automacoes.executar_manual', modulo: 'Automações', grupo: 'Controle', nome: 'Executar automação manualmente', descricao: 'Testar e rodar em lote regras em cima da base.', nivel_risk: 'alto', order: 850 },
    { key: 'automacoes.ver_logs', modulo: 'Automações', grupo: 'Monitoramento', nome: 'Ver logs de execução de automações', descricao: 'Estatísticas de falhas, rodadas automáticas e ações disparadas.', nivel_risk: 'medio', order: 860 },
    { key: 'automacoes.gerenciar', modulo: 'Automações', grupo: 'Geral', nome: 'Permissão ampla de gestão de automações', descricao: 'Gestão geral sob todas as amarras de automações.', nivel_risk: 'critico', order: 870 },
    // MACROS / RESPOSTAS PRONTAS
    { key: 'macros.visualizar', modulo: 'Macros', grupo: 'Acesso', nome: 'Ver macros', descricao: 'Ver catálogo de modelos de respostas salvas.', nivel_risk: 'baixo', order: 900 },
    { key: 'macros.criar', modulo: 'Macros', grupo: 'Modificações', nome: 'Criar macro', descricao: 'Cadastrar nova resposta rápida.', nivel_risk: 'baixo', order: 910 },
    { key: 'macros.editar', modulo: 'Macros', grupo: 'Modificações', nome: 'Editar macro', descricao: 'Corrigir gabaritos de texto rápido.', nivel_risk: 'baixo', order: 920 },
    { key: 'macros.excluir', modulo: 'Macros', grupo: 'Perigosos', nome: 'Excluir macro', descricao: 'Remover modelo de resposta rápida da lista.', nivel_risk: 'medio', order: 930 },
    { key: 'macros.usar', modulo: 'Macros', grupo: 'Uso', nome: 'Usar macro em resposta', descricao: 'Carregar layouts prontos direto no corpo das respostas.', nivel_risk: 'baixo', order: 940 },
    { key: 'macros.gerenciar', modulo: 'Macros', grupo: 'Geral', nome: 'Gestão completa', descricao: 'Supervisão ampla de macros da organização.', nivel_risk: 'medio', order: 950 },
    // BASE DE CONHECIMENTO
    { key: 'base_conhecimento.visualizar', modulo: 'Base de Conhecimento', grupo: 'Acesso', nome: 'Ver base de conhecimento', descricao: 'Acessar os artigos externos do Help Center.', nivel_risk: 'baixo', order: 1000 },
    { key: 'base_conhecimento.visualizar_interna', modulo: 'Base de Conhecimento', grupo: 'Acesso', nome: 'Ver artigos internos', descricao: 'Visualizar artigos restritos aos colaboradores.', nivel_risk: 'baixo', order: 1010 },
    { key: 'base_conhecimento.criar', modulo: 'Base de Conhecimento', grupo: 'Modificações', nome: 'Criar artigo', descricao: 'Registrar esboços de manuais na wiki.', nivel_risk: 'baixo', order: 1020 },
    { key: 'base_conhecimento.editar', modulo: 'Base de Conhecimento', grupo: 'Modificações', nome: 'Editar artigo', descricao: 'Corrigir e atualizar tópicos de manuais da empresa.', nivel_risk: 'baixo', order: 1030 },
    { key: 'base_conhecimento.publicar', modulo: 'Base de Conhecimento', grupo: 'Ações', nome: 'Publicar artigo', descricao: 'Tornar o artigo disponível online na Web.', nivel_risk: 'medio', order: 1040 },
    { key: 'base_conhecimento.despublicar', modulo: 'Base de Conhecimento', grupo: 'Ações', nome: 'Despublicar artigo', descricao: 'Reverter estado de publicado de volta a rascunho.', nivel_risk: 'baixo', order: 1055 },
    { key: 'base_conhecimento.excluir', modulo: 'Base de Conhecimento', grupo: 'Perigosos', nome: 'Excluir artigo', descricao: 'Apagar definitivamente postagens da base de conhecimento.', nivel_risk: 'medio', order: 1060 },
    { key: 'base_conhecimento.gerenciar_categorias', modulo: 'Base de Conhecimento', grupo: 'Estruturação', nome: 'Gerenciar categorias da base', descricao: 'Cadastrar as pastas organizadoras da wiki.', nivel_risk: 'baixo', order: 1070 },
    { key: 'base_conhecimento.gerenciar', modulo: 'Base de Conhecimento', grupo: 'Geral', nome: 'Gestão ampla da base de conhecimento', descricao: 'Acesso irrestrito ao editor de artigos.', nivel_risk: 'medio', order: 1080 },
    // RELATÓRIOS
    { key: 'relatorios.visualizar', modulo: 'Relatórios', grupo: 'Acesso', nome: 'Ver módulo de relatórios', descricao: 'Acessar indicadores de desempenho.', nivel_risk: 'baixo', order: 1100 },
    { key: 'relatorios.ver_operacional', modulo: 'Relatórios', grupo: 'Estatísticas', nome: 'Ver relatórios operacionais', descricao: 'Métricas de volumetria, canais mais usados, horários de pico.', nivel_risk: 'baixo', order: 1110 },
    { key: 'relatorios.ver_sla', modulo: 'Relatórios', grupo: 'Estatísticas', nome: 'Ver relatórios de SLA', descricao: 'Auditar se as metas estão sendo vencidas e por quem.', nivel_risk: 'medio', order: 1120 },
    { key: 'relatorios.ver_atendentes', modulo: 'Relatórios', grupo: 'Estatísticas', nome: 'Ver desempenho por atendente', descricao: 'Visão individualizada do tempo de resolução e CSAT de cada operador.', nivel_risk: 'medio', order: 1130 },
    { key: 'relatorios.ver_satisfacao', modulo: 'Relatórios', grupo: 'Estatísticas', nome: 'Ver CSAT', descricao: 'Avaliações coletadas com comentários de encerramento.', nivel_risk: 'baixo', order: 1140 },
    { key: 'relatorios.ver_todos_usuarios', modulo: 'Relatórios', grupo: 'Escopo', nome: 'Ver dados de todos os colaboradores', descricao: 'Permissões para acessar inteligência gerencial indiscriminada.', nivel_risk: 'medio', order: 1150 },
    { key: 'relatorios.ver_apenas_proprio', modulo: 'Relatórios', grupo: 'Escopo', nome: 'Ver apenas próprios indicadores', descricao: 'Permitir analisar estritamente seu gráfico de desempenho.', nivel_risk: 'baixo', order: 1160 },
    { key: 'relatorios.exportar', modulo: 'Relatórios', grupo: 'Ações', nome: 'Exportar CSV/Excel', descricao: 'Extrair listagem de chamados e tempos em planilhas externas.', nivel_risk: 'medio', order: 1175 },
    { key: 'relatorios.agendar', modulo: 'Relatórios', grupo: 'Automações', nome: 'Agendar relatórios futuros', descricao: 'Enviar periodicamente relatórios no e-mail de diretores.', nivel_risk: 'medio', order: 1180 },
    { key: 'relatorios.gerenciar', modulo: 'Relatórios', grupo: 'Geral', nome: 'Gestão completa de relatórios', descricao: 'Gerir modelos de dados salvos de inteligência.', nivel_risk: 'alto', order: 1190 },
    // USUÁRIOS
    { key: 'usuarios.visualizar', modulo: 'Usuários', grupo: 'Acesso', nome: 'Ver lista de usuários (Equipe)', descricao: 'Ver quem são os atendentes cadastrados na empresa.', nivel_risk: 'baixo', order: 1200 },
    { key: 'usuarios.ver_detalhes', modulo: 'Usuários', grupo: 'Visualização', nome: 'Ver detalhes de usuário', descricao: 'Visualizar dados de contato, ramal e configurações de equipe.', nivel_risk: 'baixo', order: 1210 },
    { key: 'usuarios.criar', modulo: 'Usuários', grupo: 'Modificações', nome: 'Criar usuário', descricao: 'Cadastrar novos operadores ou gestores no sistema administrativo.', nivel_risk: 'alto', order: 1220 },
    { key: 'usuarios.editar', modulo: 'Usuários', grupo: 'Modificações', nome: 'Editar usuário', descricao: 'Alterar nome, e-mail de acesso e telefone de funcionários.', nivel_risk: 'baixo', order: 1230 },
    { key: 'usuarios.desativar', modulo: 'Usuários', grupo: 'Ações', nome: 'Desativar usuário', descricao: 'Suspender temporariamente o login de um assistente.', nivel_risk: 'medio', order: 1240 },
    { key: 'usuarios.reativar', modulo: 'Usuários', grupo: 'Ações', nome: 'Reativar usuário', descricao: 'Permitir novamente o acesso de um usuário suspenso.', nivel_risk: 'baixo', order: 1250 },
    { key: 'usuarios.excluir', modulo: 'Usuários', grupo: 'Perigosos', nome: 'Excluir usuário', descricao: 'Apagar o perfil e credenciais administrativas.', nivel_risk: 'critico', order: 1260 },
    { key: 'usuarios.resetar_senha', modulo: 'Usuários', grupo: 'Correção', nome: 'Resetar senha de usuário', descricao: 'Gerar link ou substituir credenciais básicas em caso de esquecimento.', nivel_risk: 'alto', order: 1270 },
    { key: 'usuarios.alterar_perfil', modulo: 'Usuários', grupo: 'Sensíveis', nome: 'Alterar perfil (Role)', descricao: 'Atribuir nova função (Ex: Atendente para Gestor).', nivel_risk: 'critico', order: 1280 },
    { key: 'usuarios.alterar_empresa', modulo: 'Usuários', grupo: 'Sensíveis', nome: 'Alterar empresa vinculada', descricao: 'Trocar o escopo multitenant de um atendente ou cliente.', nivel_risk: 'alto', order: 1290 },
    { key: 'usuarios.gerenciar_permissoes', modulo: 'Usuários', grupo: 'Supervisores', nome: 'Gerenciar permissões de usuários', descricao: 'Atribuir privilégios manuais, allowance e denial de privilégios aos membros da empresa.', nivel_risk: 'critico', order: 1300 },
    { key: 'usuarios.ver_permissoes', modulo: 'Usuários', grupo: 'Visualização', nome: 'Ver permissões efetivas de usuários', descricao: 'Investigar matriz resolvida de acessos por colaborador.', nivel_risk: 'medio', order: 1310 },
    { key: 'usuarios.gerenciar', modulo: 'Usuários', grupo: 'Geral', nome: 'Gestão completa de usuários', descricao: 'Poder administrativo absoluto sobre todos operadores.', nivel_risk: 'critico', order: 1320 },
    // EMPRESAS
    { key: 'empresas.visualizar', modulo: 'Empresas', grupo: 'Acesso', nome: 'Ver empresas', descricao: 'Listar empresas clientes cadastradas.', nivel_risk: 'baixo', order: 1400 },
    { key: 'empresas.ver_detalhes', modulo: 'Empresas', grupo: 'Visualização', nome: 'Ver detalhes da empresa', descricao: 'Ficha técnica com CNPJ, contatos corporativos e notas.', nivel_risk: 'baixo', order: 1410 },
    { key: 'empresas.criar', modulo: 'Empresas', grupo: 'Modificações', nome: 'Criar empresa', descricao: 'Cadastrar nova corporação no banco para vincular clientes.', nivel_risk: 'medio', order: 1420 },
    { key: 'empresas.editar', modulo: 'Empresas', grupo: 'Modificações', nome: 'Editar empresa', descricao: 'Editar dados corporativos e contratos.', nivel_risk: 'baixo', order: 1430 },
    { key: 'empresas.desativar', modulo: 'Empresas', grupo: 'Ações', nome: 'Desativar empresa', descricao: 'Bloquear login de todos os clientes pertencentes a esta empresa cliente.', nivel_risk: 'medio', order: 1440 },
    { key: 'empresas.excluir', modulo: 'Empresas', grupo: 'Perigosos', nome: 'Excluir empresa', descricao: 'Apagar corporações inteiras de forma irreversível.', nivel_risk: 'critico', order: 1450 },
    { key: 'empresas.gerenciar_email_canais', modulo: 'Empresas', grupo: 'Operação', nome: 'Gerenciar canais de e-mail da empresa', descricao: 'Configurar alias de e-mails para entrada de chamados.', nivel_risk: 'alto', order: 1460 },
    { key: 'empresas.gerenciar_configuracoes', modulo: 'Empresas', grupo: 'Operação', nome: 'Gerenciar configurações de empresa', descricao: 'Habilitar canais, customizações de logo próprias para B2B.', nivel_risk: 'medio', order: 1470 },
    { key: 'empresas.gerenciar', modulo: 'Empresas', grupo: 'Geral', nome: 'Gestão completa das empresas', descricao: 'Supervisão administrativa integral sobre os clientes jurídicos.', nivel_risk: 'alto', order: 1480 },
    // CONFIGURAÇÕES
    { key: 'configuracoes.visualizar', modulo: 'Configurações', grupo: 'Acesso', nome: 'Acessar configurações', descricao: 'Ver painéis básicos parametrizáveis.', nivel_risk: 'baixo', order: 1500 },
    { key: 'configuracoes.preferencias', modulo: 'Configurações', grupo: 'Preferências', nome: 'Ver e editar preferências gerais', descricao: 'Parametrizar configurações menores.', nivel_risk: 'baixo', order: 1515 },
    { key: 'configuracoes.empresa', modulo: 'Configurações', grupo: 'Preferências', nome: 'Configurar dados da empresa sede', descricao: 'Atualizar contatos padrões e políticas globais.', nivel_risk: 'medio', order: 1520 },
    { key: 'configuracoes.atendimento', modulo: 'Configurações', grupo: 'Preferências', nome: 'Configurar central de chamados', descricao: 'Mudar status válidos, tipos de chamado padrão e campos obrigatórios.', nivel_risk: 'alto', order: 1530 },
    { key: 'configuracoes.sistema', modulo: 'Configurações', grupo: 'Segurança', nome: 'Ver configurações de sistema', descricao: 'Sincronizações críticas do Gestifique.', nivel_risk: 'alto', order: 1540 },
    { key: 'configuracoes.gerenciar', modulo: 'Configurações', grupo: 'Geral', nome: 'Gestão completa de configurações', descricao: 'Controle mestre de todas as telas administrativas.', nivel_risk: 'critico', order: 1550 },
    // TELAS PÚBLICAS
    { key: 'telas.visualizar', modulo: 'Telas Públicas', grupo: 'Acesso', nome: 'Ver painel de telas públicas', descricao: 'Olhar as áreas editáveis de site externo.', nivel_risk: 'baixo', order: 1600 },
    { key: 'telas.precos.visualizar', modulo: 'Telas Públicas', grupo: 'Preços', nome: 'Ver editores de planos', descricao: 'Olhar o portfólio de assinaturas público.', nivel_risk: 'baixo', order: 1610 },
    { key: 'telas.precos.editar', modulo: 'Telas Públicas', grupo: 'Preços', nome: 'Editar planos, preços e textos', descricao: 'Redigir valores, termos de contratação e FAQ públicos.', nivel_risk: 'critico', order: 1620 },
    { key: 'telas.precos.resetar', modulo: 'Telas Públicas', grupo: 'Preços', nome: 'Reverter configurações de preços para o original', descricao: 'Apagar alterações em lote devolvendo aos padrões de fábrica.', nivel_risk: 'alto', order: 1630 },
    { key: 'telas.home.editar', modulo: 'Telas Públicas', grupo: 'Futuro', nome: 'Editar Home Pública', descricao: 'Ajustar imagens e logotipos públicos da capa.', nivel_risk: 'baixo', order: 1640 },
    { key: 'telas.funcionalidades.editar', modulo: 'Telas Públicas', grupo: 'Futuro', nome: 'Editar Funcionalidades', descricao: 'Modificar carrosséis de produtos secundários.', nivel_risk: 'baixo', order: 1650 },
    { key: 'telas.contato.editar', modulo: 'Telas Públicas', grupo: 'Futuro', nome: 'Editar contatos', descricao: 'Substituir e-mails de canais de suporte no rodapé público.', nivel_risk: 'baixo', order: 1660 },
    { key: 'telas.gerenciar', modulo: 'Telas Públicas', grupo: 'Geral', nome: 'Gestão irrestrita das telas públicas', descricao: 'Mudar qualquer dado das landing pages do software.', nivel_risk: 'alto', order: 1670 },
    // PORTAL DO CLIENTE
    { key: 'portal.visualizar', modulo: 'Portal do Cliente', grupo: 'Acesso', nome: 'Ver portal do cliente', descricao: 'Visão externa do cliente.', nivel_risk: 'baixo', order: 1700 },
    { key: 'portal.configurar', modulo: 'Portal do Cliente', grupo: 'Geral', nome: 'Configurar portal', descricao: 'Ativar subdomínios, termos de uso.', nivel_risk: 'medio', order: 1710 },
    { key: 'portal.personalizar', modulo: 'Portal do Cliente', grupo: 'Geral', nome: 'Personalizar Portal', descricao: 'Mudança de cores e banner de entrada.', nivel_risk: 'baixo', order: 1720 },
    { key: 'portal.ver_tickets_cliente', modulo: 'Portal do Cliente', grupo: 'Histórico', nome: 'Ver chamados próprios no portal', descricao: 'Visualização permitida ao usuário cliente de seus chamados abertos.', nivel_risk: 'baixo', order: 1730 },
    { key: 'portal.criar_ticket', modulo: 'Portal do Cliente', grupo: 'Operação', nome: 'Abertura de chamado no portal', descricao: 'Inserção de novos chamados.', nivel_risk: 'baixo', order: 1740 },
    { key: 'portal.responder_ticket', modulo: 'Portal do Cliente', grupo: 'Operação', nome: 'Fazer comentários/respostas no portal', descricao: 'Interação direta de mensagens.', nivel_risk: 'baixo', order: 1750 },
    { key: 'portal.gerenciar_acesso', modulo: 'Portal do Cliente', grupo: 'Segurança', nome: 'Gerenciar links mágicos sem senha', descricao: 'Alterar regras de autenticação.', nivel_risk: 'medio', order: 1765 },
    // IA
    { key: 'ia.visualizar', modulo: 'Inteligência Artificial', grupo: 'Acesso', nome: 'Ver assistente IA', descricao: 'Visualizar aba da IA ou botão de bot no menu lateral.', nivel_risk: 'baixo', order: 1800 },
    { key: 'ia.chat.usar', modulo: 'Inteligência Artificial', grupo: 'Uso', nome: '[LEGADO] Usar chat interativo livre', descricao: 'Legado. Conversar livremente na aba Chat com IA para tirar dúvidas da base.', nivel_risk: 'baixo', order: 1810 },
    { key: 'ia.chat', modulo: 'Inteligência Artificial', grupo: 'Chat', nome: 'Conversar com o assistente IA', descricao: 'Enviar perguntas ao assistente IA do sistema.', nivel_risk: 'medio', order: 1815 },
    { key: 'ia.ticket.resumir', modulo: 'Inteligência Artificial', grupo: 'Produtividade', nome: '[LEGADO] Gerar resumo automático de chamados', descricao: 'Legado. Usar o LLM para digerir a timeline de interações e gerar um breve texto contextual.', nivel_risk: 'baixo', order: 1820 },
    { key: 'ia.usar_resumo', modulo: 'Inteligência Artificial', grupo: 'Chamados', nome: 'Gerar resumo de chamado', descricao: 'Usar IA para resumir conversas de chamados.', nivel_risk: 'medio', order: 1825 },
    { key: 'ia.ticket.sugerir_resposta', modulo: 'Inteligência Artificial', grupo: 'Produtividade', nome: '[LEGADO] Sugerir repostas com Inteligência Artificial', descricao: 'Legado. Montar layouts e sugerir respostas completas de atendimento ao cliente.', nivel_risk: 'baixo', order: 1830 },
    { key: 'ia.sugerir_resposta', modulo: 'Inteligência Artificial', grupo: 'Chamados', nome: 'Sugerir resposta com IA', descricao: 'Gerar sugestões de resposta para chamados usando IA.', nivel_risk: 'medio', order: 1835 },
    { key: 'ia.ticket.triagem_automatica', modulo: 'Inteligência Artificial', grupo: 'Geral', nome: '[LEGADO] Triagem automática inteligente', descricao: 'Legado. Mover categoria ou preencher dados de SLA via IA.', nivel_risk: 'alto', order: 1840 },
    { key: 'ia.triagem', modulo: 'Inteligência Artificial', grupo: 'Chamados', nome: 'Ver triagem inteligente', descricao: 'Ver sentimento, categoria ou classificação sugerida por IA.', nivel_risk: 'medio', order: 1845 },
    { key: 'ia.ticket.alterar_prioridade_automaticamente', modulo: 'Inteligência Artificial', grupo: 'Avançado', nome: '[LEGADO] Mudança inteligente de prioridade', descricao: 'Legado. Autorizar a IA a mudar prioridade de chamados ativamente conforme sentimento.', nivel_risk: 'alto', order: 1850 },
    { key: 'ia.configurar', modulo: 'Inteligência Artificial', grupo: 'Geral', nome: 'Definir credenciais e comportamentos de IA', descricao: 'Mudar a personalidade padrão do robô e prompts internos.', nivel_risk: 'critico', order: 1860 },
    { key: 'ia.ver_status', modulo: 'Inteligência Artificial', grupo: 'Sistema', nome: 'Monitorar status e saúde da IA', descricao: 'Ver se chaves API estão corretas e monitoramento.', nivel_risk: 'baixo', order: 1870 },
    { key: 'ia.ver_logs', modulo: 'Inteligência Artificial', grupo: 'Sistema', nome: 'Ver logs de uso da IA', descricao: 'Relatórios de volumetria dos tokens utilizados pelas chamadas.', nivel_risk: 'medio', order: 1880 },
    { key: 'ia.gerenciar', modulo: 'Inteligência Artificial', grupo: 'Geral', nome: 'Gestão completa do motor cognitivo', descricao: 'Super privilégio de configuração da IA.', nivel_risk: 'critico', order: 1890 },
    // AUDITORIA
    { key: 'auditoria.visualizar', modulo: 'Auditoria', grupo: 'Acesso', nome: 'Ver logs do sistema', descricao: 'Acessar painel de logs.', nivel_risk: 'medio', order: 1900 },
    { key: 'auditoria.ver_logs_usuarios', modulo: 'Auditoria', grupo: 'Estatísticas', nome: 'Ver logs de usuários', descricao: 'Visualizar login, alteração cadastral por operador.', nivel_risk: 'medio', order: 1910 },
    { key: 'auditoria.ver_logs_tickets', modulo: 'Auditoria', grupo: 'Estatísticas', nome: 'Ver logs de chamados', descricao: 'Averiguar remoção de mensagens e exclusões de anexos.', nivel_risk: 'medio', order: 1920 },
    { key: 'auditoria.ver_logs_permissoes', modulo: 'Auditoria', grupo: 'Estatísticas', nome: 'Ver histórico de privilégios de acessos', descricao: 'Relatórios detalhados de quem deu grant ou deny e quando.', nivel_risk: 'alto', order: 1930 },
    { key: 'auditoria.exportar', modulo: 'Auditoria', grupo: 'Ações', nome: 'Exportar logs de auditoria', descricao: 'Extrair listagem de auditoria.', nivel_risk: 'alto', order: 1940 },
    { key: 'auditoria.gerenciar', modulo: 'Auditoria', grupo: 'Geral', nome: 'Gestão irrestrita de auditorias', descricao: 'Configurar retenção de dados históricos e segurança.', nivel_risk: 'critico', order: 1950 },
    // NOTIFICAÇÕES
    { key: 'notificacoes.visualizar', modulo: 'Notificações', grupo: 'Acesso', nome: 'Ver notificações', descricao: 'Acessar central de alertas pessoais.', nivel_risk: 'baixo', order: 2000 },
    { key: 'notificacoes.marcar_lida', modulo: 'Notificações', grupo: 'Ações', nome: 'Marcar como lida', descricao: 'Arquivar notificações velhas.', nivel_risk: 'baixo', order: 2010 },
    { key: 'notificacoes.gerenciar', modulo: 'Notificações', grupo: 'Geral', nome: 'Configurar notificações globais', descricao: 'Acionar alertas SMTP ou webhook de disparo das rotinas.', nivel_risk: 'medio', order: 2020 },
    { key: 'notificacoes.enviar_manual', modulo: 'Notificações', grupo: 'Ações', nome: 'Enviar notificação manual', descricao: 'Enviar comunicados globais em massa pela central.', nivel_risk: 'alto', order: 2030 },
    // SATISFAÇÃO / CSAT
    { key: 'satisfacao.visualizar', modulo: 'Satisfação (CSAT)', grupo: 'Acesso', nome: 'Visualizar avaliações', descricao: 'Olhar as notas individuais deixadas pelos clientes.', nivel_risk: 'baixo', order: 2100 },
    { key: 'satisfacao.ver_relatorios', modulo: 'Satisfação (CSAT)', grupo: 'Estatísticas', nome: 'Ver relatórios de CSAT', descricao: 'Indicador de First Contact Resolution (FCR) e satisfação de encerramento.', nivel_risk: 'baixo', order: 2110 },
    { key: 'satisfacao.configurar', modulo: 'Satisfação (CSAT)', grupo: 'Geral', nome: 'Configurar questionário e gatilho de CSAT', descricao: 'Editar escala de pontuação (carinhas, 5 estrelas) e textos da pesquisa.', nivel_risk: 'medio', order: 2120 },
    { key: 'satisfacao.gerenciar', modulo: 'Satisfação (CSAT)', grupo: 'Geral', nome: 'Gestão completa do pós-venda', descricao: 'Supervisão do índice geral CSAT da corporação.', nivel_risk: 'medio', order: 2130 },
    // INTEGRAÇÕES / CANAIS
    { key: 'integracoes.visualizar', modulo: 'Integrações', grupo: 'Acesso', nome: 'Ver integrações', descricao: 'Visualizar canais SMTP, IMAP unificados.', nivel_risk: 'baixo', order: 2200 },
    { key: 'integracoes.email.visualizar', modulo: 'Integrações', grupo: 'Canais de E-mail', nome: 'Ver canais de e-mail', descricao: 'E-mails ativos de leitura IMAP para captura automática.', nivel_risk: 'baixo', order: 2210 },
    { key: 'integracoes.email.criar', modulo: 'Integrações', grupo: 'Canais de E-mail', nome: 'Criar canal de e-mail', descricao: 'Vincular nova conta IMAP/SMTP.', nivel_risk: 'alto', order: 2220 },
    { key: 'integracoes.email.editar', modulo: 'Integrações', grupo: 'Canais de E-mail', nome: 'Editar canal de e-mail', descricao: 'Editar credenciais, portas TLS, servidores.', nivel_risk: 'alto', order: 2230 },
    { key: 'integracoes.email.excluir', modulo: 'Integrações', grupo: 'Canais de E-mail', nome: 'Excluir canal de e-mail', descricao: 'Desconectar e excluir a caixa de e-mail.', nivel_risk: 'critico', order: 2240 },
    { key: 'integracoes.email.testar', modulo: 'Integrações', grupo: 'Canais de E-mail', nome: 'Testar canal de e-mail', descricao: 'Fazer o ping de diagnóstico nas credenciais cadastradas.', nivel_risk: 'medio', order: 2250 },
    { key: 'integracoes.whatsapp.visualizar', modulo: 'Integrações', grupo: 'Outros Canais', nome: 'Ver WhatsApp', descricao: 'Visualizar status da integração WhatsApp.', nivel_risk: 'baixo', order: 2260 },
    { key: 'integracoes.whatsapp.gerenciar', modulo: 'Integrações', grupo: 'Outros Canais', nome: 'Gerenciar WhatsApp', descricao: 'Habilitar bot de atendimento receptivo WhatsApp.', nivel_risk: 'alto', order: 2270 },
    { key: 'integracoes.webhooks.gerenciar', modulo: 'Integrações', grupo: 'Avançado', nome: 'Gerenciar Webhooks', descricao: 'Cadastrar end-points de notificação reativos aos chamados.', nivel_risk: 'alto', order: 2280 },
    { key: 'integracoes.gerenciar', modulo: 'Integrações', grupo: 'Geral', nome: 'Gestão irrestrita de integrações', descricao: 'Super privilégio de conectores.', nivel_risk: 'critico', order: 2290 },
    // SISTEMA
    { key: 'sistema.visualizar', modulo: 'Sistema', grupo: 'Segurança', nome: 'Visualizar área de sistema', descricao: 'Status operacional dos servidores.', nivel_risk: 'medio', order: 2300 },
    { key: 'sistema.health', modulo: 'Sistema', grupo: 'Monitoramento', nome: 'Acompanhar health checks', descricao: 'Acompanhar fila de execuções em segundo plano.', nivel_risk: 'baixo', order: 2310 },
    { key: 'sistema.configurar', modulo: 'Sistema', grupo: 'Segurança', nome: 'Configurações técnicas', descricao: 'Configurações intrínsecas ao kernel do software.', nivel_risk: 'critico', order: 2320 },
    { key: 'sistema.ver_variaveis', modulo: 'Sistema', grupo: 'Monitoramento', nome: 'Ver variáveis de ambiente', descricao: 'Apurar a existência dos tokens sem vazar os segredos.', nivel_risk: 'alto', order: 2330 },
    { key: 'sistema.executar_manutencao', modulo: 'Sistema', grupo: 'Ações', nome: 'Executar tarefas de manutenção', descricao: 'Limpeza de logs antigos e reindexação de tabelas.', nivel_risk: 'critico', order: 2340 },
    { key: 'sistema.developer', modulo: 'Sistema', grupo: 'Geral', nome: 'Área exclusiva de desenvolvedor', descricao: 'Executar comandos diretamente ou depuração de migrações.', nivel_risk: 'critico', order: 2350 },
    { key: 'sistema.super_admin', modulo: 'Sistema', grupo: 'Geral', nome: 'Acesso total irrestrito', descricao: 'Super permissão mestre.', nivel_risk: 'critico', order: 2360 },
    // PERFIL
    { key: 'perfil.visualizar', modulo: 'Perfil', grupo: 'Geral', nome: 'Visualizar próprio perfil', descricao: 'Acessar suas configurações de avatar pessoais.', nivel_risk: 'baixo', order: 2400 },
    { key: 'perfil.editar', modulo: 'Perfil', grupo: 'Geral', nome: 'Editar próprio perfil', descricao: 'Alterar nome, telefone pessoal.', nivel_risk: 'baixo', order: 410 },
    { key: 'perfil.alterar_senha', modulo: 'Perfil', grupo: 'Geral', nome: 'Alterar própria senha', descricao: 'Atualizar senha pessoal.', nivel_risk: 'baixo', order: 2420 },
    { key: 'perfil.configurar_preferencias', modulo: 'Perfil', grupo: 'Geral', nome: 'Configurar preferências de notificação pessoais', descricao: 'Ligar ou desligar som de alertas, temas favoritos.', nivel_risk: 'baixo', order: 2430 },
];
export const DEFAULT_ROLE_PERMISSIONS = {
    desenvolvedor: ['*'],
    administrador: ['*'],
    gestor: [
        'dashboard.visualizar',
        'dashboard.ver_indicadores_globais',
        'dashboard.ver_sla',
        'tickets.visualizar',
        'tickets.ver_todos',
        'tickets.ver_sem_responsavel',
        'tickets.ver_detalhes',
        'tickets.criar',
        'tickets.criar_para_cliente',
        'tickets.editar',
        'tickets.editar_titulo',
        'tickets.editar_descricao',
        'tickets.editar_categoria',
        'tickets.editar_servico',
        'tickets.editar_prioridade',
        'tickets.editar_status',
        'tickets.finalizar',
        'tickets.fechar',
        'tickets.reabrir',
        'tickets.arquivar',
        'tickets.atribuir',
        'tickets.assumir',
        'tickets.transferir',
        'tickets.remover_responsavel',
        'tickets.acoes_em_massa',
        'tickets.ver_timeline',
        'tickets.ver_tags',
        'tickets.gerenciar_tags',
        'ticket_mensagens.visualizar',
        'ticket_mensagens.responder',
        'ticket_mensagens.comentar_interno',
        'ticket_mensagens.ver_internos',
        'ticket_mensagens.anexar',
        'ticket_mensagens.baixar_anexos',
        'sla.visualizar',
        'sla.ver_relatorios',
        'automacoes.visualizar',
        'automacoes.criar',
        'automacoes.editar',
        'automacoes.ativar_desativar',
        'automacoes.ver_logs',
        'automacoes.gerenciar',
        'macros.visualizar',
        'macros.criar',
        'macros.editar',
        'macros.excluir',
        'macros.usar',
        'macros.gerenciar',
        'base_conhecimento.visualizar',
        'base_conhecimento.visualizar_interna',
        'base_conhecimento.criar',
        'base_conhecimento.editar',
        'base_conhecimento.publicar',
        'base_conhecimento.gerenciar',
        'relatorios.visualizar',
        'relatorios.ver_operacional',
        'relatorios.ver_sla',
        'relatorios.ver_atendentes',
        'relatorios.ver_satisfacao',
        'relatorios.ver_todos_usuarios',
        'relatorios.exportar',
        'usuarios.visualizar',
        'usuarios.ver_detalhes',
        'configuracoes.visualizar',
        'configuracoes.atendimento',
        'configuracoes.gerenciar',
        'ia.visualizar',
        'ia.chat.usar',
        'ia.chat',
        'ia.ticket.resumir',
        'ia.usar_resumo',
        'ia.ticket.sugerir_resposta',
        'ia.sugerir_resposta',
        'ia.triagem',
        'ia.ver_status',
        'auditoria.visualizar',
        'auditoria.ver_logs_tickets',
        'notificacoes.visualizar',
        'notificacoes.marcar_lida',
        'satisfacao.visualizar',
        'satisfacao.ver_relatorios',
    ],
    atendente: [
        'dashboard.visualizar',
        'dashboard.ver_indicadores_proprios',
        'dashboard.ver_sla',
        'tickets.visualizar',
        'tickets.ver_todos',
        'tickets.ver_detalhes',
        'tickets.criar',
        'tickets.editar',
        'tickets.editar_titulo',
        'tickets.editar_descricao',
        'tickets.editar_status',
        'tickets.finalizar',
        'tickets.reabrir',
        'tickets.assumir',
        'tickets.ver_timeline',
        'tickets.ver_tags',
        'ticket_mensagens.visualizar',
        'ticket_mensagens.responder',
        'ticket_mensagens.comentar_interno',
        'ticket_mensagens.ver_internos',
        'ticket_mensagens.anexar',
        'ticket_mensagens.baixar_anexos',
        'macros.visualizar',
        'macros.usar',
        'base_conhecimento.visualizar',
        'base_conhecimento.visualizar_interna',
        'base_conhecimento.criar',
        'base_conhecimento.editar',
        'ia.visualizar',
        'ia.chat.usar',
        'ia.chat',
        'ia.ticket.resumir',
        'ia.usar_resumo',
        'ia.ticket.sugerir_resposta',
        'ia.sugerir_resposta',
        'notificacoes.visualizar',
        'notificacoes.marcar_lida',
    ],
    cliente: [
        'portal.visualizar',
        'portal.ver_tickets_cliente',
        'portal.criar_ticket',
        'portal.responder_ticket',
        'base_conhecimento.visualizar',
        'perfil.visualizar',
        'perfil.editar',
    ]
};
