import { Router } from 'express';
import  authRoutes from  './auth.routes.js';
import  userRoutes from  './users.routes.js';
import  ticketRoutes from  './tickets.routes.js';
import  dashboardRoutes from  './dashboard.routes.js';
import  profileRoutes from  './profile.routes.js';
import  logsRoutes from  './logs.routes.js';
import  attachmentRoutes from  './attachments.routes.js';
import  reportsRoutes from  './reports.routes.js';
import  notificationsRoutes from  './notifications.routes.js';
import  macrosRoutes from './macros.routes.js';
import  satisfactionRoutes from './satisfaction.routes.js';
import  automationsRoutes from './automations.routes.js';
import  portalAuthRoutes from './portal-auth.routes.js';
import { portalRoutes } from './portal.routes.js';
import { emailChannelsRoutes } from './email-channels.routes.js';
import emailTestRoutes from './email-test.routes.js';
import healthRoutes from './health.routes.js';
import aiRoutes from './ai.routes.js';
import permissionsRoutes from './permissions.routes.js';
import accessProfilesRoutes from './access-profiles.routes.js';
import internalJobsRoutes from './internal-jobs.routes.js';
import internalOutboxRoutes from './internal-outbox.routes.js';
import whatsappRoutes from './whatsapp.routes.js';
import ticketSettingsRoutes from './ticket-settings.routes.js';
import applicationSettingsRoutes from './application-settings.routes.js';
import obligationsRoutes from './obligations.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/tickets', ticketRoutes);
router.use('/ticket-settings', ticketSettingsRoutes);
router.use('/application-settings', applicationSettingsRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/profile', profileRoutes);
router.use('/logs', logsRoutes);
router.use('/attachments', attachmentRoutes);
router.use('/reports', reportsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/macros', macrosRoutes);
router.use('/satisfaction', satisfactionRoutes);
router.use('/automations', automationsRoutes);
router.use('/portal-auth', portalAuthRoutes);
router.use('/portal', portalRoutes);
router.use('/health', healthRoutes);
router.use('/email-test', emailTestRoutes);
router.use('/ai', aiRoutes);
router.use('/permissions', permissionsRoutes);
router.use('/access-profiles', accessProfilesRoutes);
router.use('/internal/jobs', internalJobsRoutes);
router.use('/internal/outbox', internalOutboxRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/obligations', obligationsRoutes);
router.use('/', emailChannelsRoutes);

export default router;
